apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    ocelot.social/selector: deployment-ocelot-social-mailserver
  name: mailserver
  namespace: docker-mailserver
spec:
  minReadySeconds: 15
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      ocelot.social/selector: deployment-ocelot-social-mailserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: data
      creationTimestamp: null
      labels:
        ocelot.social/selector: deployment-ocelot-social-mailserver
      name: mailserver
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: docker-mailserver-configmap
        # - secretRef:
        #     name: XXX
        image: tvial/docker-mailserver:release-v7.2.0
        imagePullPolicy: Always
        name: mailserver
        ports:
        - containerPort: 25
          protocol: TCP
        - containerPort: 143
          protocol: TCP
        - containerPort: 587
          protocol: TCP
        - containerPort: 993
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:  # taken from: https://github.com/funkypenguin/helm-docker-mailserver/blob/master/charts/docker-mailserver/templates/deployment.yaml
        - name: config
          mountPath: /tmp/docker-mailserver
        - name: ssl-cert  # !!! is this really needed ???
          mountPath: /tmp/ssl
          readOnly: true              
        - name: data
          mountPath: /var/mail
          subPath: mail
        - name: data
          mountPath: /var/mail-state
          subPath: mail-state
        - name: configmap
          subPath: dovecot-services.cf
          mountPath: /etc/dovecot/conf.d/services.cf
          readOnly: true  
        - name: configmap
          subPath: dovecot.cf
          mountPath: /etc/dovecot/conf.d/zz-custom.cf
          readOnly: true  
        - name: configmap
          subPath: TrustedHosts
          mountPath: /tmp/docker-mailserver/opendkim/TrustedHosts
          readOnly: true                        
        - name: configmap
          subPath: SigningTable
          mountPath: /tmp/docker-mailserver/opendkim/SigningTable
          readOnly: true    
        - name: configmap
          subPath: KeyTable
          mountPath: /tmp/docker-mailserver/opendkim/KeyTable
          readOnly: true   
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: "data"
        persistentVolumeClaim:
          claimName: docker-mailserver-data-claim
      - name: "config"
        emptyDir: {}
      - name: "configmap"
        configMap:
          # name: {{ template "dockermailserver.fullname" . }}-configs
          name: XXX
      # - name: "opendkim-keys"
      #   secret:
      #     secretName: {{ template "dockermailserver.fullname" . }}-secrets
      - name: "ssl-cert"  # !!! is this really needed ???
        secret:
          secretName: tls  # ATTENTION: needs same namespace! see: https://kubernetes.io/docs/concepts/configuration/secret/#restrictions
status: {}
