apiVersion: v1
kind: Service
metadata:
  name: mailserver
  namespace: docker-mailserver
  labels:
    ocelot.social/selector: deployment-ocelot-social-mailserver
spec:
  ports:  # names overtaken from here: https://github.com/funkypenguin/helm-docker-mailserver/blob/master/charts/docker-mailserver/values.yaml
  - name: smtp
    port: 25
    targetPort: 25
  - name: imap
    port: 143
    targetPort: 143
  - name: submission
    port: 587
    targetPort: 587
  - name: imaps
    port: 993
    targetPort: 993
  selector:
    ocelot.social/selector: deployment-ocelot-social-mailserver
