apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    ocelot.social/selector: deployment-ocelot-social-mailserver
  name: mailserver
  namespace: ocelot-social
spec:
  minReadySeconds: 15
  progressDeadlineSeconds: 60
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      ocelot.social/selector: deployment-ocelot-social-mailserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        ocelot.social/selector: deployment-ocelot-social-mailserver
      name: mailserver
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: configmap
        - secretRef:
            name: ocelot-social
        image: djfarrelly/maildev
        imagePullPolicy: Always
        name: mailserver
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 25
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
